# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Colloquy-Bot-Simple
version:      1.05
version_from: lib/Colloquy/Bot/Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Chatbot::TalkerBot:            1.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
